import { Layout } from '../components/Layout';
import { ChevronRight } from 'lucide-react';
import { Link } from 'react-router-dom';

export function Q12026DigitalAssetMarketQuarterlyReport() {
  const p = 'mb-6 text-lg leading-relaxed text-slate-300';
  const h2 = 'text-xl sm:text-2xl md:text-3xl font-bold leading-snug tracking-tight text-white mt-12 mb-6';
  const h3 = 'text-2xl font-bold text-white mt-12 mb-6 tracking-tight';

  return (
    <Layout>
      <article className="min-h-screen bg-gradient-to-b from-[#0A0A0A] via-[#050505] to-[#0A0A0A] relative font-sans">
        <div className="max-w-5xl mx-auto px-4 py-8 relative z-10">
          <nav className="flex items-center gap-2 text-sm text-gray-500 mb-8">
            <Link to="/" className="hover:text-white transition-colors">Home</Link>
            <ChevronRight size={14} />
            <Link to="/insights" className="hover:text-white transition-colors">Insights</Link>
            <ChevronRight size={14} />
            <span className="text-gray-400">Q1 2026 Market Report</span>
          </nav>

          <div className="mb-16">
            <div className="inline-block bg-transparent border border-indigo-500 text-indigo-400 rounded-md px-2 py-1 text-xs font-bold tracking-widest uppercase mb-6">
              QUARTERLY REPORT
            </div>

            <h1 className="text-3xl sm:text-4xl md:text-5xl font-bold leading-tight tracking-tight text-white mb-4">
              Q1 2026 Market Report: Macro Realignment & On-chain Evolution
            </h1>

            <p className="text-slate-400 text-lg mt-4 mb-8">
              By Nexus One Research Desk • Apr 5, 2026 • 35 min read
            </p>
          </div>

          <div className="max-w-5xl mx-auto text-lg leading-relaxed text-slate-300 font-sans">
            <section className="mb-12">
              <h2 className={h2}>TL;DR: Key Takeaways</h2>
              <ul className="list-disc pl-6 space-y-4 mb-6 text-lg leading-relaxed text-slate-300 marker:text-slate-500">
                <li><strong className="text-slate-200">Macro Headwinds &amp; Market Correction:</strong> Geopolitical shocks in the Middle East and sticky inflation delayed Fed rate cuts, shifting Q1 into a severe correction phase where Bitcoin fell 22% and Ethereum dropped up to 35%.</li>
                <li><strong className="text-slate-200">Spot ETF Reallocation:</strong> U.S. Spot Bitcoin ETFs saw 4 months of outflows before reversing with a $1.32B influx in March. Solana ETFs demonstrated unprecedented resilience, capturing consistent institutional inflows.</li>
                <li><strong className="text-slate-200">L1 &amp; L2 Divergence:</strong> Ethereum transitioned into a settlement layer as the Fusaka upgrade fueled L2 dominance (Base &amp; Arbitrum capturing 77% of L2 TVL). Meanwhile, Solana achieved the #1 spot in on-chain revenue ($26.7M/month), validating its monolithic high-performance model.</li>
                <li><strong className="text-slate-200">RWA &amp; Stablecoin Surge:</strong> RWA assets surged 66% to nearly $27.6B, heavily driven by tokenized U.S. Treasuries. Stablecoins approached a $300B market cap, handling over $34T in annualized settlement volume.</li>
                <li><strong className="text-slate-200">Mega Narratives - Prediction Markets &amp; AI Agents:</strong> Polymarket volumes exploded 20x to $21B/month due to geopolitical betting. Agentic Commerce became a reality, with blockchains acting as the essential micro-transaction settlement rail for AI agents.</li>
                <li><strong className="text-slate-200">Regulatory Milestones:</strong> Expected Q2 passage of the CLARITY Act and the implementation of the GENIUS Act (Stablecoin framework) are poised to eliminate regulatory uncertainty and open the floodgates for institutional capital.</li>
              </ul>
            </section>

            <section className="mb-12">
              <h2 className={h2}>1. Global Macroeconomic Trends and Ripple Effects on Traditional Financial Markets</h2>
              <p className={p}>In Q1 2026, the global macroeconomic environment experienced extreme volatility due to a combination of geopolitical shocks in the Middle East and concerns over sticky inflation. In particular, the escalation of the conflict between the U.S. and Iran that broke out in late February acted as a core driver extremely stimulating Risk-off sentiment in global capital markets. As the threat of a blockade in the Strait of Hormuz—through which approximately 20% of global crude oil and gas cargo volume passes—emerged, fears of a global supply chain collapse spread. Consequently, Brent Crude prices surged to the $114 per barrel mark at one point, evoking market fear of reignited inflation (WTI crude oil closed trading at the $103 level).</p>
              <p className={p}>This geopolitical instability and the surge in energy prices forced major central banks to immediately revise their monetary policy trajectories. The U.S. Federal Reserve (Fed), at the Federal Open Market Committee (FOMC) meeting held on March 18, froze the federal funds rate at 3.50~3.75%, assessing that geopolitical shocks were making it difficult to achieve its Dual Mandate of price stability and maximum employment. Fed Chair Jerome Powell, in an interview at Harvard University, reaffirmed his commitment to achieving the 2% inflation target, but noted that trade tariffs had a one-off effect of pushing up inflation by 0.5% to 1%, and that the Fed is closely monitoring the impact of the Middle East situation on gasoline prices. Conversely, Fed Governor Stephen Miran assessed that the rise in oil prices has not yet transmitted to inflation expectations and that the possibility of a wage-price spiral is low, exposing diverging views even within the Fed.</p>
              <p className={p}>Nevertheless, as of the end of Q1, the swap market began pricing in the possibility of a rate freeze throughout 2026, which means the expectations for early rate cuts that were prevalent in the market at the beginning of the year have completely evaporated. The European Central Bank (ECB) also froze its deposit rate at 2.0% citing energy price volatility, and, reflecting the energy shock, downgraded the Eurozone growth forecast for 2026 to 0.9% while upgrading the inflation forecast to 2.6%. As uncertainty in macroeconomic indicators deepened, the Dollar Index (DXY) rose to the 100.48 level, and the 10-year U.S. Treasury yield repeatedly fluctuated in a high range between 4.31% and 4.44% in the latter half of Q1, reflecting anxiety in the bond market. Conversely, as safe-haven preference was maximized, international Gold prices used $4,418 per ounce as a support line and broke through $4,530, continuing a streak of all-time highs.</p>
              <p className={p}>These macroeconomic headwinds acted as structural downward pressure on the digital asset market. Geopolitical shocks, coupled with corrections in the stock market, compelled investors to reduce risk exposure across their portfolios. Bitcoin, in particular, saw its traditionally asserted &apos;Digital Gold (safe haven)&apos; narrative partially activate, showing robust relative strength against the Nasdaq or Gold temporarily in the early stages of the Iran conflict. Ultimately, however, it failed to overcome liquidity contraction and macro anxiety, revealing a high correlation as a Risk-on asset that fully absorbed the shocks of the stock market. As a result, the digital asset market in Q1 underwent a harsh re-evaluation process as a dependent variable of the macroeconomy amidst the double whammy of delayed inflation slowdown and retreating rate cut expectations.</p>
            </section>

            <section className="mb-12">
              <h2 className={h2}>2. Overall Digital Asset Market Performance and On-chain Investor Sentiment Analysis</h2>
              <p className={p}>The virtual asset market in Q1 2026 lost the euphoric bullish momentum of the previous year and entered a phase of full-scale correction and structural realignment. The market optimism that peaked in Q4 2025, especially in early October when Bitcoin broke its All-Time High (ATH) of $126,000, froze rapidly due to geopolitical tensions and unexpected Tariff Shocks. During Q1, the total market capitalization of virtual assets dropped by about 20% to 22%, experiencing a severe contraction where the $2.5 trillion line collapsed at one point.</p>
              <p className={p}>Looking at the performance of major assets, Bitcoin (BTC) recorded a 22% quarterly decline rate, finishing trading in the $64,000 to $68,000 band at the end of March. This is a 45% drop from its peak. The decline of Ethereum (ETH), ranked 2nd in market cap, was even more pronounced. Ethereum fell by 29% to up to 35% during the quarter, sliding to a quarterly low of $1,820 on February 6, recording a level 56% lower than its previous high. This market-wide plunge is analyzed as the result of the aftermath of liquidity depletion left by the massive $19 billion cascading leverage liquidation event that occurred on October 10 last year, which persisted into Q1.</p>

              <div className="overflow-x-auto my-8">
                <table className="w-full text-left border-collapse border border-slate-800 text-sm sm:text-base">
                  <thead>
                    <tr className="border-b border-slate-800 bg-slate-900/50">
                      <th className="py-3 px-4 text-slate-300 font-semibold border-b border-slate-800">Asset &amp; Indicator</th>
                      <th className="py-3 px-4 text-slate-300 font-semibold border-b border-slate-800">Q4 2025 Peak</th>
                      <th className="py-3 px-4 text-slate-300 font-semibold border-b border-slate-800">End of Q1 2026</th>
                      <th className="py-3 px-4 text-slate-300 font-semibold border-b border-slate-800">Quarterly Change Rate</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr className="border-b border-slate-800 bg-slate-900/50">
                      <td className="py-3 px-4 text-white font-medium border-b border-slate-800">Total Crypto Market Cap</td>
                      <td className="py-3 px-4 text-slate-300 border-b border-slate-800">~$3.3T (Approached)</td>
                      <td className="py-3 px-4 text-slate-300 border-b border-slate-800">~$2.3T ~ $2.5T</td>
                      <td className="py-3 px-4 text-slate-300 border-b border-slate-800">-20% ~ -22%</td>
                    </tr>
                    <tr className="border-b border-slate-800">
                      <td className="py-3 px-4 text-white font-medium border-b border-slate-800">Bitcoin (BTC) Price</td>
                      <td className="py-3 px-4 text-slate-300 border-b border-slate-800">$126,000</td>
                      <td className="py-3 px-4 text-slate-300 border-b border-slate-800">$64,000 ~ $68,511</td>
                      <td className="py-3 px-4 text-slate-300 border-b border-slate-800">-22% (-45% from peak)</td>
                    </tr>
                    <tr className="border-b border-slate-800 bg-slate-900/50">
                      <td className="py-3 px-4 text-white font-medium border-b border-slate-800">Ethereum (ETH) Price</td>
                      <td className="py-3 px-4 text-slate-300 border-b border-slate-800">$4,800+ (Est.)</td>
                      <td className="py-3 px-4 text-slate-300 border-b border-slate-800">$1,820 ~ $2,135</td>
                      <td className="py-3 px-4 text-slate-300 border-b border-slate-800">-29% ~ -35% (-56% from peak)</td>
                    </tr>
                    <tr className="border-b border-slate-800">
                      <td className="py-3 px-4 text-white font-medium border-b border-slate-800">Bitcoin Dominance</td>
                      <td className="py-3 px-4 text-slate-300 border-b border-slate-800">Approx. 55%</td>
                      <td className="py-3 px-4 text-slate-300 border-b border-slate-800">58.0%</td>
                      <td className="py-3 px-4 text-slate-300 border-b border-slate-800">+3.0%p</td>
                    </tr>
                  </tbody>
                </table>
              </div>

              <p className={p}>On-chain data and market sentiment indicators clearly show this deterioration of fundamentals. The MVRV Z-Score, which determines whether an asset is overvalued or undervalued by measuring the divergence between Bitcoin&apos;s market value and realized value (actual capital inflow to the network), fell significantly to between 0.42 and 0.47 as of the end of March. This suggests that the asset has completely escaped the overheating zone seen at past bull market peaks and is converging toward its long-term &apos;Fair Value&apos;. The Net Unrealized Profit/Loss (NUPL) indicator, which represents the net unrealized profit/loss within the network, also fell to the 18.82% to 20.63% level, confirming that the overall profitability of investors was compromised and market sentiment transitioned from Belief through Anxiety to the Fear stage.</p>
              <p className={p}>The &apos;Fear &amp; Greed Index&apos;, representing the short-term speculative sentiment of the market, remained in the Extreme Fear zone throughout Q1. In late March in particular, the index recorded between 13 and 26 out of 100, evidencing the deep anxiety and contracted buying sentiment of investors. However, this extreme fear index and price drop leave room to be interpreted as signs of a structural bear-market bottom. In fact, analyzing the on-chain behavioral patterns of institutional investors reveals that the selling pressure from Long-Term Holders (LTH) eased, while the active supply of Short-Term Holders (STH) of less than 3 months increased to 37%, indicating active hand-changing.</p>
              <p className={p}>A notable point is that despite the bear market, Bitcoin Dominance (market cap share) firmly maintained the 58% level. This means that rather than capital flowing out of altcoins and small-cap asset classes completely exiting the ecosystem, a &apos;Flight to Quality&apos; phenomenon is clearly operating within the virtual asset space itself, where capital concentrates into Bitcoin, the relatively safe reserve asset, amidst uncertainty. Furthermore, even while the entire smart contract-based DeFi ecosystem experienced a liquidity crisis, it was confirmed that a mature derivatives market structure is settling, with Bitcoin Options Open Interest (OI) exceeding Perpetual Futures as investors focused on downside risk hedging.</p>
            </section>

            <section className="mb-12">
              <h2 className={h2}>3. Spot ETF Fund Flows and Strategic Capital Reallocation by Institutional Investors</h2>
              <p className={p}>The fund flows of spot Exchange-Traded Funds (ETFs) in Q1 2026 served as the most transparent indicator showing how institutional capital within digital assets reacts to macroeconomic changes and reallocates assets. The U.S. spot ETF market, which achieved a record net inflow of over $50 billion since its listing in early 2024, experienced the longest winter of capital outflows since its inception entering Q1. However, by specific asset, stark temperature differences were observed depending on institutional investment preferences.</p>
              <p className={p}>Spot Bitcoin ETFs experienced large-scale redemptions for four consecutive months, starting with an outflow of $3.5 billion in November 2025, $1.1 billion in December, $1.61 billion in January 2026, and $207 million in February. The cumulative outflow during this period reached approximately $6.3 billion to $6.4 billion. Coupled with the plunge in Bitcoin prices, total ETF Assets Under Management (AUM) halved from a peak of $169.5 billion last October to about $87.5 billion by the end of Q1. Expanding geopolitical risks and the extinction of Fed rate cut expectations triggered institutional investors&apos; profit-taking and risk management selling. The Exchange Whale Ratio, which surged from 0.34 in January to 0.79 at the end of March, also supports that large institutional holders moved assets to exchanges, aggravating selling pressure.</p>
              <p className={p}>However, in March, the final month of Q1, the Bitcoin ETF market achieved a dramatic reversal. As institutional investors judged Bitcoin&apos;s $64,000 to $68,000 range as an attractive long-term entry point, a powerful net inflow of $1.32 billion occurred throughout the month of March. On a specific day (March 16), $216.2 million flowed in, driving the market&apos;s positive momentum. This capital influx in March holds symbolic meaning as a transition to monthly net inflows for the first time in 5 months, but it failed to completely offset the massive outflows in January and February. Consequently, the overall Bitcoin ETF fund flow for Q1 closed with a net outflow of approximately $496 million to $500 million.</p>

              <div className="overflow-x-auto my-8">
                <table className="w-full text-left border-collapse border border-slate-800 text-sm sm:text-base">
                  <thead>
                    <tr className="border-b border-slate-800 bg-slate-900/50">
                      <th className="py-3 px-4 text-slate-300 font-semibold border-b border-slate-800">Spot ETF Underlying Asset</th>
                      <th className="py-3 px-4 text-slate-300 font-semibold border-b border-slate-800">Q1 2026 Cumulative Fund Flow</th>
                      <th className="py-3 px-4 text-slate-300 font-semibold border-b border-slate-800">March Monthly Fund Flow</th>
                      <th className="py-3 px-4 text-slate-300 font-semibold border-b border-slate-800">Market Narrative &amp; Institutional Assessment</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr className="border-b border-slate-800 bg-slate-900/50">
                      <td className="py-3 px-4 text-white font-medium border-b border-slate-800">Bitcoin (BTC)</td>
                      <td className="py-3 px-4 text-slate-300 border-b border-slate-800">-$496M</td>
                      <td className="py-3 px-4 text-slate-300 border-b border-slate-800">+$1.32B</td>
                      <td className="py-3 px-4 text-slate-300 border-b border-slate-800">Trend reversal with low-price buying in March after 4 consecutive months of outflows.</td>
                    </tr>
                    <tr className="border-b border-slate-800">
                      <td className="py-3 px-4 text-white font-medium border-b border-slate-800">Ethereum (ETH)</td>
                      <td className="py-3 px-4 text-slate-300 border-b border-slate-800">-$769M</td>
                      <td className="py-3 px-4 text-slate-300 border-b border-slate-800">-$46M</td>
                      <td className="py-3 px-4 text-slate-300 border-b border-slate-800">3 consecutive months of outflows. Reflects declining L1 attractiveness due to value transfer to L2.</td>
                    </tr>
                    <tr className="border-b border-slate-800 bg-slate-900/50">
                      <td className="py-3 px-4 text-white font-medium border-b border-slate-800">Solana (SOL)</td>
                      <td className="py-3 px-4 text-slate-300 border-b border-slate-800">+$213M</td>
                      <td className="py-3 px-4 text-slate-300 border-b border-slate-800">Continuous Inflow</td>
                      <td className="py-3 px-4 text-slate-300 border-b border-slate-800">Recorded net inflows every month since listing. Institutional bet on overwhelming transaction performance.</td>
                    </tr>
                    <tr className="border-b border-slate-800">
                      <td className="py-3 px-4 text-white font-medium border-b border-slate-800">Ripple (XRP)</td>
                      <td className="py-3 px-4 text-slate-300 border-b border-slate-800">+$43M</td>
                      <td className="py-3 px-4 text-slate-300 border-b border-slate-800">-$31M</td>
                      <td className="py-3 px-4 text-slate-300 border-b border-slate-800">Maintained positive quarterly balance despite monthly volatility. Effect of mitigated litigation risks.</td>
                    </tr>
                  </tbody>
                </table>
              </div>

              <p className={p}>The performance of spot Ethereum ETFs delivered deep disappointment to the market. Recording a painful cumulative net outflow of $769 million without a distinct rebound throughout Q1, it posted the worst performance among all cryptocurrency ETFs. In March as well, $46 million flowed out, failing to escape the swamp of sluggishness. This suggests that as transaction and fee value within the Ethereum ecosystem rapidly migrate to Layer 2 (L2), institutional investors have begun harboring fundamental doubts about the token value appreciation logic intrinsic to Ethereum as a Layer 1 (L1). However, the fact that some companies like BitMine Immersion Technologies engaged in low-price buying—accumulating 2.7 million ETH during Q1 to build the largest corporate treasury asset of 4.73 million ETH—could act as a spark for a future rebound.</p>
              <p className={p}>The most eye-catching part is the powerful self-sustainability of alternative altcoin spot ETFs, led by Solana (SOL) and Ripple (XRP). Boosted by active support from traditional finance, such as Morgan Stanley&apos;s listing application, the spot Solana ETF achieved a cumulative net inflow of $213 million in Q1 alone. In particular, the Solana ETF recorded an unstoppable winning streak, not allowing a single month of capital outflow since its listing, showing the best performance among altcoin ETFs. The Ripple ETF also experienced an outflow of $31 million in March, but put up a good defense by recording a net inflow of $43 million for the quarter overall. This trend signifies that the &apos;structural rotation of smart money&apos; has begun in earnest, where institutional investors are diversifying their portfolios beyond the simple &apos;digital gold&apos; model into high-performance Layer 1 ecosystems that possess overwhelming actual network throughput and have proven a clear Product-Market Fit (PMF).</p>
            </section>

            <section className="mb-12">
              <h2 className={h2}>4. Layer 1 (L1) and Layer 2 (L2) Ecosystems: Hegemony Competition Based on Scalability and Economics</h2>
              <p className={p}>The blockchain network infrastructure landscape in Q1 2026 can be largely summarized by two themes. First is the market monopolization phenomenon by Rollup networks tracking Ethereum&apos;s roadmap, and second is the surge in on-chain profitability of alternative Layer 1s (Alt-L1) that adopted Monolithic structures.</p>

              <h3 className={h3}>4.1 Ethereum Ecosystem: Fusaka Upgrade and L2 Winner-Takes-All</h3>
              <p className={p}>In the Ethereum ecosystem, the effects of the Fusaka and PeerDAS upgrades, successfully applied to the mainnet on December 3, 2025, caused structural changes across the ecosystem throughout Q1. The Fusaka upgrade is a collection of core improvements designed to solve Ethereum&apos;s scalability issues. It raised the block gas limit from the existing 45 million to 60 million (EIP-7935) to increase the L1&apos;s own transactions per second, and established a gas limit cap per transaction (EIP-7825) to increase the predictability of block construction. It also maximized the mainnet&apos;s computational efficiency through MODEXP precompile fee readjustment (EIP-7883) and network protocol optimization (EIP-7642).</p>
              <p className={p}>However, the true core of the Fusaka upgrade lies in dramatically lowering the data processing costs of Layer 2 (L2) networks. Through the introduction of PeerDAS (Peer Data Availability Sampling, EIP-7594), it significantly expanded the Blob data capacity the network can process while reducing the load on individual validators. Through the BPO (Blob Parameter Only, EIP-7892) hard fork mechanism, it laid the foundation to rapidly and stably increase the data throughput of future rollups. Furthermore, by introducing a blob fee floor via EIP-7918, it attempted a structural shift to monetize the data availability costs that L2s pay to Ethereum.</p>
              <p className={p}>As a result of this technical leap, over 95% of Ethereum&apos;s total transaction throughput in Q1 2026 occurred on Layer 2, with the integrated system TPS achieving the remarkable feat of surpassing 325. Ethereum fundamentally completely transformed from a platform that processes computations into a &apos;settlement and data availability layer&apos; that manages the security and data of L2s.</p>
              <p className={p}>Looking inside the Layer 2 ecosystem reveals an extreme &apos;Winner-takes-all&apos; phenomenon. Unlike the past where dozens of L2 projects mushroomed, capital and users were thoroughly concentrated into a few top networks. <strong className="text-slate-200">Base</strong>, the Optimistic Rollup led by Coinbase, grabbed 46.58% of L2 DeFi TVL in Q1, taking an unrivaled 1st place, and showed overwhelming activity by processing over 60% of all L2 transactions. According to Q1 data, Base recorded a maximum of over 232 million User Operations (UOPS) in a single day on February 5, unmatched by other networks. Following behind, <strong className="text-slate-200">Arbitrum</strong>, which established itself as an institution-friendly DeFi hub, recorded a 30.86% TVL market share, and <strong className="text-slate-200">Optimism</strong> showed about a 12% TVL share. Conversely, despite their technical excellence, the ZK Rollup camp (zkSync, StarkNet, Scroll, etc.) remained in a niche market, failing to enter the mainstream with less than a 15% TVL share and lagging significantly in transaction throughput.</p>
              <p className={p}>Data proves that the top L2 ecosystems like Base and Arbitrum are essentially dividing the market, occupying over 77% of all Layer 2 DeFi deposits. A powerful network effect where abundant liquidity attracts more users and dApps is dominating the L2 market.</p>

              <h3 className={h3}>4.2 On-chain Revenue Generation Ability of High-Performance L1s and Solana&apos;s Sprint</h3>
              <p className={p}>While the Ethereum ecosystem underwent structural differentiation centered on L2s, high-performance monolithic Layer 1 chains that process all computations and consensus on a single layer succeeded in building explosive transaction growth and independent revenue models.</p>
              <p className={p}>Solana processed a staggering cumulative 10.1 billion transactions during Q1 2026, breaking its all-time high for a single quarter. This is a 50% surge compared to Q4 of the previous year. As of the end of March, Monthly Active Users (MAU) also surpassed 2.4 million, proving its strong dominance in the retail market. Solana&apos;s growth is attributed to the activation of the memecoin launchpad Pump.fun and Decentralized Exchanges (DEX) capable of High-Frequency Trading (HFT).</p>
              <p className={p}>What must be noted is that the quantitative expansion of transactions directly led to actual &apos;Network Revenue&apos;. During Q1, Solana generated $26.7 million in monthly network fee revenue, overtaking Ethereum ($23.2 million, 3rd place)—which had previously been like an impregnable fortress—to ascend to the 1st place in on-chain revenue among all blockchains. This means that economic activities within the Solana ecosystem are generating massive cash flows for the protocol itself.</p>
              <p className={p}>Following behind, Tron ranked 2nd with a monthly revenue of $24.4 million. Based on its low fees, Tron processes the absolute majority of global Tether (USDT) remittances, establishing a stable payment network use case in emerging markets. On the other hand, BNB Chain ($9.3 million, 4th) and Base ($8.4 million, 5th) showed a stark revenue gap with the top 3 networks. This profitability decoupling among L1s will be a core catalyst that shifts the token valuation models of each protocol from speculative expectations to indicators of actual cash flow generation ability (e.g., P/F Ratio) in the future.</p>
            </section>

            <section className="mb-12">
              <h2 className={h2}>5. Stagnation and Niche Growth of the DeFi Ecosystem and Decentralized Exchanges (DEX)</h2>
              <p className={p}>The Decentralized Finance (DeFi) ecosystem in Q1 2026 experienced an overall stagnation, taking the full brunt of macroeconomic uncertainty and the decrease in speculative liquidity. As of Q1, the total Total Value Locked (TVL) in DeFi closed at around the $116.7 billion mark, experiencing a deep correction where approximately 25% to 32% evaporated compared to the previous peak of $171.9 billion in October 2025.</p>
              <p className={p}>The sector hit hardest was the spot trading market based on Decentralized Exchanges (DEX). In Q1, the weekly spot trading volume of DEXs hovered around the $41.07 billion level, plummeting to a 1-year low. The trading share of DEXs, which showed a maximum share of over 21% against Centralized Exchange (CEX) trading volume in past bull markets, dropped significantly to 14.1% by the end of Q1. The fundamental reason for this stagnation is that due to market weakness and the high-interest-rate trend, the launch of large new projects called &apos;Star Tokens&apos; plummeted, and the blind speculative sentiment of retail investors toward memecoins and altcoins contracted significantly. Looking at each chain, the exodus of DEX trading volume from the Ethereum mainnet was the most severe, with only Solana-based DEXs struggling to maintain a volume of about $11.42 billion. At the individual protocol level, PancakeSwap maintained its #1 rank in activity, occupying about 9.9% of all DEX traffic.</p>
              <p className={p}>In contrast to the extreme slump in spot trading, the decentralized derivatives and Perpetual Futures DEX sector continued explosive growth, emerging as the core revenue source for DeFi. The trading volume of derivatives DEXs surged by over 346% from the $1.5 trillion level the previous year to an annualized $6.7 trillion scale in Q1, driving the overall decentralized trading volume. This is because on-chain orderbook platforms capable of 24-hour trading, like Hyperliquid, began handling stock indices of traditional financial assets, actively absorbing the hedging demand of institutional investors and sophisticated trading funds.</p>
              <p className={p}>In terms of diversifying DeFi revenue models, the case of the Fluid protocol stands out. Fluid, which integrates Lending and DEX functions, generated a massive Gross Protocol Revenue of $13.98 million during Q1. Among this, lending interest revenue accounted for the largest portion at $10.39 million, creating a stable cash flow alongside swap fees ($16,420) and Jupiter Lend revenue sharing. Despite a somewhat conservative average APY of 1.48%, it built an autonomous economic structure based on the platform&apos;s own fees without recklessly issuing blind token incentives (Liquidity Mining) to users. This plainly shows that the Q1 DeFi market is evolving from a simple liquidity provision competition toward a focus on capital efficiency.</p>
              <p className={p}>Meanwhile, security issues were still pointed out as the biggest Achilles heel of DeFi ecosystem growth. From late 2025 to Q1 2026, DeFi protocols suffered massive damages amounting to approximately $512 million due to smart contract vulnerabilities and hacks. In particular, over $310 million was stolen solely through attacks targeting vulnerabilities related to Decentralized Autonomous Organizations (DAOs), impressing once again that code audits and the advancement of security infrastructure are essential prerequisites for attracting institutional funds.</p>
            </section>

            <section className="mb-12">
              <h2 className={h2}>6. The Leap of Tokenized Real World Assets (RWA) and the Stablecoin Ecosystem</h2>
              <p className={p}>In the Q1 2026 virtual asset market, the sector that achieved the most explosive quantitative and qualitative growth based purely on macro fundamentals, with speculative elements excluded, was undoubtedly Real World Asset (RWA) tokenization and stablecoins. As the high-interest-rate trend prolonged, the demand to exchange non-interest-bearing Idle Crypto for yield-generating assets in the traditional system interlocked with on-chain infrastructure innovation, creating a massive capital movement.</p>

              <h3 className={h3}>6.1 Vertical Rise of the RWA Market and Asset Class Diversification</h3>
              <p className={p}>The value of tokenized RWAs on public blockchains started at approximately $14.1 billion in January 2026 and surged to about $23.6 billion by the end of March—and by some data estimates, up to $27.65 billion—recording an astonishing growth rate of over 66% compared to the beginning of the year. The protagonists driving the explosive growth of this sector are none other than tokenized funds based on U.S. Treasury Bills and Money Market Funds (MMF). Treasury tokens issued by giants of traditional finance have established themselves as the standard for Risk-free rates within the DeFi ecosystem.</p>
              <p className={p}>Specifically, while treasury tokens based on the Circle ecosystem lead the market with a 21.04% share, Ondo Finance&apos;s product lineup (USDY, OUSG, etc.) is running 2nd, occupying 18.75% with a scale of $2.4 billion. Furthermore, products based on the Securitize platform successfully deposited massive institutional funds on-chain, accounting for 17.92%, alongside BlackRock&apos;s BUIDL (approx. $2.2 billion) and Franklin Templeton&apos;s BENJI (approx. $1.0 billion). Additionally, attempts to tokenize government debt outside the U.S. are also gaining momentum, with UKTBL based on UK bonds experiencing rapid growth of 109.4% in a short period.</p>
              <p className={p}>The most encouraging change is the outward expansion of tokenized assets. Beyond treasuries, tokenized gold (XAUT $2.7B, PAXG $2.4B) and commodities grew to a scale of approximately $6.5 billion. Furthermore, as traditional exchanges like Nasdaq and the New York Stock Exchange (NYSE) expanded pilot tests of tokenized Equities, equity-linked on-chain assets formed a scale of about $4 billion.</p>
              <p className={p}>In terms of network market share, Ethereum firmly occupies 56.15% (approx. $15.5 billion) of all RWA assets, solidifying its position as the de facto Primary Chain for institutional asset issuance. A point to note is that BNB Chain jumped to 2nd place with a market share of 12.66% (approx. $3.5 billion), showing the fastest monthly growth rate of 29.44%. This proves that the strategy of dramatically increasing RWA accessibility for retail investors as well as high-net-worth individuals, using low fees as a weapon, was highly effective. Besides this, the Stellar and Plume networks showed meaningful growth by targeting specific niche markets with market shares of 5.10% and 1.27%, respectively.</p>

              <h3 className={h3}>6.2 Stablecoins: A $300 Billion Global Payment Infrastructure</h3>
              <p className={p}>The stablecoin ecosystem, the core medium for safe assets and payments, surpassed $299.4 billion in total issued market capitalization, closing in fast on the $300 billion milestone. The total number of stablecoin-holding wallets increased by 4.25% in 30 days to 242.15 million, proving broad global adoption. According to statistics from Visa, the annualized on-chain payment processing volume of stablecoins as of Q1 exceeded a staggering $34 trillion, reaching a level where it practically replaces traditional cross-border remittance networks (like SWIFT) beyond serving as a simple bridge for virtual asset trading. In particular, the volume of B2B (Business-to-Business) stablecoin payments surged from under $100 million per month in 2023 to a recent scale of $6.0 billion per month, solidifying its practicality as corporate financial infrastructure.</p>
              <p className={p}>The market share structure remains an overwhelmingly duopolistic system, cementing its structure. Tether (USDT) maintained its issuance level between $183.6 billion and $185.6 billion, dominating 59.3% of the entire market and defending its immovable #1 spot. Following this, Circle&apos;s USDC captured a 24.6% share with an issuance volume of approximately $74.1 billion to $76.0 billion, cementing a structure where these two assets monopolize 83.9% of the world&apos;s decentralized liquidity. Meanwhile, DAI, the leader of collateral-based decentralized stablecoins, showed a high growth rate of 8.83% over 30 days, recording a scale of $4.7 billion and continuing to serve as a major pillar of the ecosystem.</p>
            </section>

            <section className="mb-12">
              <h2 className={h2}>7. New Mega Narratives: The Blossoming of Agentic Commerce and Prediction Markets</h2>
              <p className={p}>The most innovative and disruptive trend piercing through Q1 2026 was the explosive growth of &apos;Prediction Markets&apos; and AI-driven &apos;Agentic Commerce&apos;, created by the combination of blockchain infrastructure with real-life use cases and other cutting-edge technologies.</p>

              <h3 className={h3}>7.1 Exponential Expansion of Prediction Markets: The Polymarket Phenomenon</h3>
              <p className={p}>While the broader DeFi ecosystem struggled with declining liquidity, the only sector that recorded phenomenal traffic growth was prediction market platforms represented by Polymarket. Prediction market trading volume, which was merely a niche market of $1.2 billion per month at the end of 2025, exploded nearly 20-fold to over $21.0 billion per month in Q1 2026, elevating it to the ranks of mainstream financial products. The number of monthly Unique Wallets also nearly tripled in 6 months, surpassing 840,000, broadening its base from the exclusive domain of a few speculators to a mass market.</p>
              <p className={p}>At the base of this exponential growth lies extreme global geopolitical crises. Sweeping the top spots in Polymarket trading volume were entirely bets related to the outbreak of war and geopolitics involving the U.S., Iran, and Israel. In particular, a massive $73 million in capital—the largest in Polymarket&apos;s history—concentrated on a single contract: &quot;Will the U.S. directly strike Iran by February 28, 2026?&quot; Another $63 million poured into the bet: &quot;Will Israel launch a ground war in Lebanon by March 31?&quot; As Google Finance and mainstream media officially began citing Polymarket&apos;s Odds as indicators for real-time polling and risk hedging, blockchain-based prediction markets fully established themselves as real-time collective intelligence platforms replacing traditional intelligence analysis agencies.</p>

              <h3 className={h3}>7.2 Commercialization of Agentic Commerce: Convergence of AI and Blockchain Payment Infrastructure</h3>
              <p className={p}>The second core narrative is the full-scale commercialization of &apos;Agentic Commerce&apos;, where Artificial Intelligence (AI) agents autonomously search, compare products, and execute final payments independently without consumer intervention. 2026 will be recorded as the inaugural year when this concept moved beyond pilot operations and began directly impacting massive macroeconomic revenues reaching trillions of dollars. According to research by McKinsey and others, Agentic Commerce is projected to generate massive retail revenues of $3 trillion to $5 trillion globally by 2030. Over 90% of corporate leaders are confident that AI agents will process at least 20% of their online orders by 2027.</p>
              <p className={p}>The essential infrastructure to run this massive AI economic engine is the blockchain-based Settlement Rail. AI agents cannot fill out complex identity verification forms of traditional finance or swipe credit cards. They require instant and frictionless value transfer programmatically via APIs, and need a payment network capable of repeating Micro-transactions of less than 1 cent per data request tens of thousands of times.</p>
              <p className={p}>In response to this, the adoption of blockchain by global payment companies opened like floodgates during Q1 2026. OpenAI and Stripe launched the &apos;Agentic Commerce Protocol&apos;, an AI transaction standard, and Google also unveiled the &apos;Universal Commerce Protocol&apos; with over 30 fintech partners. In particular, Coinbase introduced the &apos;x402 standard&apos;, an extension of the HTTP 402 protocol, to its Layer 2 Base network, perfectly processing over 15 million payments between AI agents on the blockchain in Q1 alone. In the Asian market, Alipay announced that weekly agentic payment transactions utilizing AI surpassed 120 million, proving the explosive adoption of AI-native commerce. Consequently, the growth of Agentic Commerce clearly demonstrated that blockchain networks and stablecoins are converging into the indispensable &apos;Base Settlement Protocol&apos; of the forthcoming AI-centric economy, moving beyond simple financial assets.</p>
            </section>

            <section className="mb-12">
              <h2 className={h2}>8. Korean Digital Asset Market Trends: Collapse of Trading Volume and Structural Ecosystem Realignment</h2>
              <p className={p}>The Republic of Korea&apos;s digital asset market in Q1 2026 suffered the aftereffects of the so-called &apos;Crypto Frenzy&apos;, passing through the tunnel of a harsh cooling period and massive restructuring.</p>

              <h3 className={h3}>8.1 Contraction of Retail Investment Sentiment and the Exodus of Massive Capital</h3>
              <p className={p}>The most prominent feature of the domestic market is the record-breaking plunge in trading volume. According to data analytics firm ZDNet Korea, the cumulative trading volume of Korean virtual asset exchanges evaporated by a staggering 80%, from 371.4 trillion KRW in the same quarter last year to 77.6 trillion KRW in Q1 this year. The &apos;Kimchi Premium&apos;, which once represented the heat of the Korean market while leading global prices, completely vanished, converging to near 0%.</p>
              <p className={p}>A complex interplay of KRW exchange rate weakness and global macroeconomic uncertainty lay behind this trading drought. As the USD/KRW exchange rate soared to threaten the 1,500 KRW line during Q1, anxious domestic high-net-worth individuals and institutional investors began proactively cashing out their funds. According to blockchain data analytics firm Allium Labs, the stablecoin balances of wallets associated with Korea&apos;s top 5 KRW-market exchanges (Upbit, Bithumb, Coinone, Korbit, Gopax) plummeted by over 55%, from $575 million in the second half of 2025 to $188 million by mid-March. During the same period, exchange Broker deposits also evaporated by about 19 trillion KRW, from 131 trillion KRW to 112 trillion KRW. This clearly shows that rather than simply taking a break from virtual asset investments, investors sold dollar-pegged stablecoins, exchanged them for KRW, and executed an &apos;Exodus&apos;—moving their capital en masse into traditional asset markets like U.S. equities backed by earnings or stable domestic real estate.</p>

              <h3 className={h3}>8.2 Deepening Skew Towards Upbit and Bithumb&apos;s Fatal Risk</h3>
              <p className={p}>The environment of severe liquidity contraction drove the polarization of the domestic exchange ecosystem to the extreme. Even amidst an overall plunge in trading volume, Upbit, the market leader, occupied an overwhelming market share ranging from 58.4% to a peak of 80%, demonstrating a virtual monopoly over Korea&apos;s crypto infrastructure. Conversely, Bithumb, the 2nd largest exchange, committed fatal operational blunders due to internal control failures, causing its market share to collapse to the 24.8% level.</p>
              <p className={p}>On February 6, Bithumb caused a massive Fat-finger incident where, instead of paying &apos;2,000 KRW&apos; worth of Bitcoin to customers as an event reward, it paid &apos;2,000 BTC&apos; per person due to an internal network input error. As a result, a staggering 620,000 Bitcoins were incorrectly recorded on customer ledgers—a fictitious quantity exceeding the total holdings of 42,800 BTC disclosed by Bithumb at the time by more than 14 times. Immediately following this incident, which caused fundamental distrust in the exchange&apos;s ledger management and asset segregation systems beyond a simple input mistake, Bithumb&apos;s market share plummeted from 31.5% to the low 20% range. To resolve the situation, Bithumb launched a completely free fee campaign, temporarily recovering its share to the 30% line, but it fell back to the mid-20% range immediately after the campaign ended, failing to recover its damaged trust in the short term. Instead, regulatory pressure intensified, cornering them, as the Fair Trade Commission (FTC) conducted a search and seizure of their Gangnam headquarters to investigate whether the phrase &quot;Securing the highest level of liquidity in Korea&quot; claimed in Bithumb&apos;s past advertisements constituted false or exaggerated advertising. Meanwhile, Coinone (13%), Korbit (3.5%), and Gopax (0.3%) remained at marginal market shares, failing to form a meaningful competitive landscape.</p>

              <h3 className={h3}>8.3 The Crisis of the KAIA Blockchain and the LINE Integration Gambit</h3>
              <p className={p}>The domestic Korean blockchain ecosystem, which was struggling in the global Layer 1 competition, threw its final gambit for survival. KAIA, which was ambitiously launched in August 2024 through the mainnet integration of Kakao&apos;s Klaytn and Naver LINE&apos;s Finschia, experienced a severe liquidity crisis throughout Q1. The DeFi Total Value Locked (TVL) of the KAIA ecosystem, which stood at approximately $39.87 million right after launch, plummeted to the $13 million level, evaporating by about 70% due to the absence of attractive killer DApps to drive the ecosystem. Harsh criticisms followed that they neglected the exodus of existing users without presenting practical use cases for the blockchain.</p>
              <p className={p}>To find a breakthrough, the Kaia DLT Foundation accelerated attracting institutional capital and building Real World Asset (RWA) tokenization infrastructure in Q1 2026, building upon the &apos;Kaia Wave&apos; program (launching 30 mini-DApps within the LINE messenger) unveiled in Q1 2025. During Q1, KAIA collaborated with Singaporean regulatory platform InvestaX to successfully tokenize &apos;Pegasus 1&apos;, a $25 million Liquefied Natural Gas (LNG) vessel financing project. They then opened an additional $1.5 million &apos;Pegasus 2&apos; round, pioneering a unique use case of transitioning maritime finance on-chain. Furthermore, by officially integrating JPYC, Japan&apos;s JPY-pegged stablecoin, into the Web3 wallet (Unifi) within the LINE app, they laid the foundation to provide remittance and payment utility to 100 million domestic Japanese users. Whether this infrastructure and social platform integration work concentrated in Q1 can lead to actual user traffic and value creation (TVL rebound) in Q2 will be a crucial testing ground for the revival of the Korean blockchain ecosystem.</p>
            </section>

            <section className="mb-12">
              <h2 className={h2}>9. Global Regulatory Framework: Accelerating Institutionalization for Institutional Entry</h2>
              <p className={p}>The global digital asset regulatory environment in Q1 2026 was a crucial watershed where the efforts of legislators to control risks while embracing innovation materialized into specific legislative enactments and approvals from regulatory bodies.</p>
              <p className={p}>The core issue that concentrated the most market attention is the <strong className="text-slate-200">CLARITY Act (Digital Asset Market Structure Bill)</strong>, which is currently drifting in the U.S. Senate Banking Committee. This bill possesses a market-friendly framework that defines most virtual assets as Commodities rather than Securities, transferring jurisdiction to the CFTC and clarifying the regulatory boundaries for exchanges and custodians. However, during the Senate review process early in the year, the passage of the bill was delayed as sharp conflicts arose between the traditional banking sector and the virtual asset industry over &quot;whether to allow stablecoin issuers to pay Yield and rewards.&quot; Traditional banks demanded a total ban, arguing that allowing interest payments would cause massive Deposit Flight, while the industry, including Coinbase, pushed back citing the hindrance of consumer benefits.</p>
              <p className={p}>However, at the end of Q1, significant progress was captured in the sluggish negotiations. As of early April, Coinbase&apos;s Chief Legal Officer Paul Grewal stated in a media interview, &quot;A compromise with the banking sector regarding stablecoin interest payments is nearly finalized, and there will be tangible progress within 48 hours,&quot; significantly raising market expectations. The compromise, led by Senator Thom Tillis and others, is known to have taken the direction of restricting interest payments on Passive balances, while allowing rewards based on specific &apos;Activities&apos;. Coinbase argued that there were no actual signs of deposit flight due to stablecoins, but expressed a strong will to reach an agreement for the greater good and lead a Senate vote within Q2. If the CLARITY Act is passed, the regulatory uncertainty that has been the biggest barrier to entry for institutional investors will be resolved at once, serving as a historic catalyst for massive capital inflows.</p>
              <p className={p}>In parallel, the GENIUS Act, a standalone stablecoin regulation bill, entered the practical implementation phase after its legislation was completed on July 18, 2025. On April 1, 2026, the U.S. Treasury Department published a Notice of Proposed Rulemaking (NPRM) for the enforcement of the GENIUS Act, unveiling a &apos;Substantially similar&apos; framework that allows small to medium-sized stablecoin issuers with total issuance under $10 billion to choose State-level regulation instead of federal regulation. This is evaluated as a measure promoting the healthy fostering of the stablecoin ecosystem by compromising between centralized control and state autonomy.</p>
              <p className={p}>Also, the U.S. Office of the Comptroller of the Currency (OCC) granting conditional approval for a &apos;National Trust Bank&apos; license to Coinbase on April 2 was a symbolic event heralding the physical integration of traditional financial infrastructure and digital assets. Through this license, Coinbase is officially able to perform digital asset custody business for institutions as a &apos;Qualified Custodian&apos; complying with SEC regulations under the supervision of a single federal regulatory body, the OCC, moving beyond state-by-state fragmented Money Transmitter Licenses (MTL).</p>
              <p className={p}>Regulatory overhaul proceeded breathlessly in regions outside the U.S. as well. In particular, as the grace period for exchanges and brokers under the European Union&apos;s (EU) comprehensive virtual asset regulation, <strong className="text-slate-200">MiCA (Markets in Crypto-Assets)</strong>, fully ends as of July 1, 2026, companies operating in Europe set out to acquire massive licenses and recruit compliance personnel. In the short term, this will cause a restructuring that suppresses the mushrooming of small and medium-sized exchanges, but in the long term, it will serve as the foundation to elevate the European market into the safest and most transparent digital asset hub globally. Comprehensively, the global regulatory trends in Q1 2026 moved beyond merely suppressing the market; they were a process of building a &apos;legitimate pipeline&apos; to safely guide trillions of dollars of traditional capital on-chain while minimizing friction with the existing financial system.</p>
            </section>

            <section className="mb-12">
              <h2 className={h2}>10. Conclusion and Q2 Strategic Outlook</h2>
              <p className={p}>Superficially, the digital asset market in Q1 2026 had to endure the pain of severe price drops and contracting investor sentiment amidst the double whammy of macroeconomic headwinds and geopolitical crises. However, looking beneath the surface reveals that it was a very healthy period of &apos;Structural Reset&apos; where the irrational bubble centered on speculative memecoins cleared, and the intrinsic utility and fundamentals of blockchain established themselves as the market&apos;s new valuation standards.</p>
              <p className={p}>Ethereum&apos;s Fusaka upgrade resolved the Layer 2-centric scalability dilemma, birthing the massive economic blocs of Base and Arbitrum, while Solana and Tron maximized the advantages of high-performance single chains to generate overwhelming network cash flows. Above all, the explosive growth of Real World Asset (RWA) tokenization and the adoption of stablecoins as Agentic Commerce payment rails proved that digital asset infrastructure has finally begun a meaningful chemical bonding with the giant industries of traditional finance and Artificial Intelligence.</p>
              <p className={p}>The direction of the market in the upcoming Q2 will be dictated by the following three core Catalysts. First is whether the U.S.-Iran conflict reaches a diplomatic settlement and oil prices stabilize. If macro risks are resolved, institutional Dry Powder, which has been suppressed throughout Q1, could flexibly flow back into major virtual assets that have become more attractive in valuation. Second is the fund trends in the ETF market. If the transition to net inflows of spot Bitcoin ETFs confirmed in March and the rapid progress of altcoin ETFs like Solana continue, the market will enter a &apos;portfolio diversification by smart money&apos; phase. Third, and the most important variable, is whether the U.S. Senate passes the CLARITY Act. If this bill, which will instantly eliminate regulatory uncertainty, succeeds in legislation within Q2 through bipartisan agreement, the floodgates for global financial institutions will open, and the virtual asset market will welcome a true &apos;Super Cycle&apos; based on mature infrastructure.</p>
              <p className={p}>Rather than being swayed by short-term volatility, it is time for investors to adopt a selective and strategic approach by shifting their focus to areas of actual value creation within the on-chain ecosystem, such as the actual revenue generated by protocols, RWAs, and prediction markets. The digital asset ecosystem has crossed an irreversible threshold, evolving beyond the one-dimensional narrative of a &apos;store of value&apos; into the indispensable &apos;Settlement Rail&apos; supporting the next-generation intelligent digital economy.</p>
            </section>

            <div className="mt-16 pt-8 border-t border-slate-800/50">
              <div className="mb-8">
                <h4 className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-3">Disclaimer</h4>
                <p className="text-xs text-slate-500 leading-relaxed text-justify">
                  This report is for informational purposes only and does not constitute financial, investment, legal, or tax advice. The views expressed herein are those of the Nexus One Research Desk as of the date of publication and are subject to change without notice.
                  <br /><br />
                  Nexus One and its affiliates may hold long or short positions in the assets discussed and may adjust these positions at any time. Digital asset investments are highly volatile and involve a significant risk of loss. Investors should conduct their own due diligence.
                </p>
              </div>
              <div className="border-t border-slate-800/50 pt-6">
                <Link to="/insights" className="group inline-flex items-center gap-2 text-indigo-400 hover:text-indigo-300 transition-colors font-medium text-sm">
                  <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="transition-transform group-hover:-translate-x-1"><path d="m12 19-7-7 7-7"/><path d="M19 12H5"/></svg>
                  Back to All Insights
                </Link>
              </div>
            </div>
          </div>
        </div>
      </article>
    </Layout>
  );
}
